apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: runner
    repoURL: https://github.com/cawwot/crossplane-box
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runners
type: Opaque
data:
  runner-token: eW91ci1hY3R1YWwtdG9rZW4tdmFsdWU=
