# The XRD definition remains the same at the top
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgitlabrunners.gitlab.organization.io
spec:
  group: gitlab.organization.io
  names:
    kind: XGitLabRunner
    plural: xgitlabrunners
  claimNames:
    kind: GitLabRunner
    plural: gitlabrunners
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    projectId:
                      type: string
                    runnerEnvironment:
                      type: string
                      default: "dev"
                    department:
                      type: string
                      default: "devops"
                    instanceClass:
                      type: string
                      default: "lightweight"
                    computeResources:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: "1"
                        memory:
                          type: string
                          default: "2Gi"
                  required: ["projectId"]
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitlabrunners.gitlab.organization.io
spec:
  compositeTypeRef:
    apiVersion: gitlab.organization.io/v1alpha1
    kind: XGitLabRunner
  resources:
    - name: runner-namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-local  # Reference to our provider config
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: gitlab-runners

    - name: runner-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-local  # Reference to our provider config
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: gitlab-runner-config
                namespace: gitlab-runners
              data:
                config.toml: |
                  concurrent = 4
                  check_interval = 30
                  [[runners]]
                    [runners.kubernetes]
                      image = "ubuntu:22.04"
                      privileged = false
                      namespace = "gitlab-runners"
                      poll_timeout = 600
                      cpu_request = "${spec.parameters.computeResources.cpu}"
                      cpu_limit = "${spec.parameters.computeResources.cpu}"
                      memory_request = "${spec.parameters.computeResources.memory}"
                      memory_limit = "${spec.parameters.computeResources.memory}"

    - name: runner-token
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-local  # Reference to our provider config
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: gitlab-runner-token
                namespace: gitlab-runners
              type: Opaque
              stringData:
                runner-token: ${RUNNER_TOKEN}

    - name: runner-deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-local  # Reference to our provider config
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: gitlab-runner
                template:
                  metadata:
                    labels:
                      app: gitlab-runner
                      runner-class: ${spec.parameters.instanceClass}
                      department: ${spec.parameters.department}
                      runner-env: ${spec.parameters.runnerEnvironment}
                      os: linux
                      arch: amd64
                  spec:
                    containers:
                      - name: gitlab-runner
                        image: gitlab/gitlab-runner:latest
                        resources:
                          requests:
                            cpu: ${spec.parameters.computeResources.cpu}
                            memory: ${spec.parameters.computeResources.memory}
                          limits:
                            cpu: ${spec.parameters.computeResources.cpu}
                            memory: ${spec.parameters.computeResources.memory}
                        env:
                          - name: CUSTOM_ENV_CI_RUNNER_TAGS
                            value: "env=${spec.parameters.runnerEnvironment},project=all,os=linux,arch=amd64,dept=${spec.parameters.department},cluster=${spec.parameters.instanceClass}"
                        volumeMounts:
                          - name: config
                            mountPath: /etc/gitlab-runner
                            readOnly: true
                          - name: docker-socket
                            mountPath: /var/run/docker.sock
                    volumes:
                      - name: config
                        configMap:
                          name: gitlab-runner-config
                      - name: docker-socket
                        hostPath:
                          path: /var/run/docker.sock
