apiVersion: gitlab.organization.io/v1alpha1
kind: GitLabRunner
metadata:
  name: local-runner
spec:
  parameters:
    projectId: "12345"
    runnerEnvironment: "dev"
    department: "devops"
    instanceClass: "featherweight"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runners
type: Opaque
data:
  runner-token: eW91ci1hY3R1YWwtdG9rZW4tdmFsdWU=
