apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitlabrunners.gitlab.organization.io
spec:
  compositeTypeRef:
    apiVersion: gitlab.organization.io/v1alpha1
    kind: XGitLabRunner
  resources:
    # Namespace
    - name: runner-namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: gitlab-runners

    # Secret
    - name: runner-token
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: gitlab-runner-token
                namespace: gitlab-runners
              type: Opaque
              stringData:
                runner-token:
                  valueFrom:
                    secretKeyRef:
                      name: gitlab-runner-token
                      key: runner-token

    # Service Account
    - name: runner-sa
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners

    # ConfigMap with runner configuration
    - name: runner-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: gitlab-runner-config
                namespace: gitlab-runners
              data:
                config.toml: |
                  concurrent = 4
                  check_interval = 30
                  [[runners]]
                    [runners.kubernetes]
                      image = "ubuntu:22.04"
                      privileged = false
                      namespace = "gitlab-runners"
                      poll_timeout = 600
                      cpu_request = "1"
                      cpu_limit = "1"
                      memory_request = "2Gi"
                      memory_limit = "2Gi"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.computeResources.cpu
          toFieldPath: spec.forProvider.manifest.data.config\.toml
          transforms:
            - type: string
              string:
                fmt: |
                  concurrent = 4
                  check_interval = 30
                  [[runners]]
                    [runners.kubernetes]
                      image = "ubuntu:22.04"
                      privileged = false
                      namespace = "gitlab-runners"
                      poll_timeout = 600
                      cpu_request = "%s"
                      cpu_limit = "%s"
                      memory_request = "2Gi"
                      memory_limit = "2Gi"

    # Deployment
    - name: runner-deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners
              spec:
                replicas: 3
                selector:
                  matchLabels:
                    app: gitlab-runner
                template:
                  metadata:
                    labels:
                      app: gitlab-runner
                  spec:
                    serviceAccountName: gitlab-runner
                    containers:
                      - name: gitlab-runner
                        image: gitlab/gitlab-runner:latest
                        resources:
                          requests:
                            cpu: "1"
                            memory: "2Gi"
                          limits:
                            cpu: "1"
                            memory: "2Gi"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.instanceClass
          toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.runner-class
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.department
          toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.department
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.runnerEnvironment
          toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.runner-env
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.computeResources.cpu
          toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].resources.requests.cpu
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.computeResources.cpu
          toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].resources.limits.cpu
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.computeResources.memory
          toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].resources.requests.memory
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.computeResources.memory
          toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].resources.limits.memory
