apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgitlabrunners.gitlab.organization.io
spec:
  group: gitlab.organization.io
  names:
    kind: XGitLabRunner
    plural: xgitlabrunners
  claimNames:
    kind: GitLabRunner
    plural: gitlabrunners
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    projectId:
                      type: string
                      description: "GitLab project ID for runner registration"
                    runnerEnvironment:
                      type: string
                      default: "dev"
                    department:
                      type: string
                      default: "devops"
                    instanceClass:
                      type: string
                      default: "lightweight"
                  required: ["projectId"]
