apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitlabrunners.gitlab.organization.io
spec:
  compositeTypeRef:
    apiVersion: gitlab.organization.io/v1alpha1
    kind: XGitLabRunner
  resources:
    # Namespace
    - name: runner-namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: gitlab-runners

    # Service Account
    - name: runner-sa
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners

    # ConfigMap with runner configuration
    - name: runner-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: gitlab-runner-config
                namespace: gitlab-runners
              data:
                config.toml: |
                  concurrent = 4
                  check_interval = 30
                  [[runners]]
                    name = "{{ .parameters.instanceClass }}-runner"
                    executor = "docker"
                    [runners.custom_build_dir]
                    [runners.cache]
                      Type = "s3"
                      Path = "gitlab-runner"
                      Shared = true
                      [runners.cache.s3]
                        ServerAddress = "s3.amazonaws.com"
                        BucketName = "{{ .parameters.s3BucketName }}"
                        Insecure = false
                    [runners.docker]
                      tls_verify = false
                      image = "{{ .parameters.runnerImage }}"
                      privileged = false
                      disable_entrypoint_overwrite = false
                      oom_kill_disable = false
                      disable_cache = false
                      volumes = ["/cache"]
                      shm_size = 0
                    [runners.kubernetes]
                      namespace = "gitlab-runners"
                      poll_timeout = 600
                      {{- if eq .parameters.instanceClass "featherweight" }}
                      cpu_request = "500m"
                      cpu_limit = "500m"
                      memory_request = "1Gi"
                      memory_limit = "1Gi"
                      {{- else if eq .parameters.instanceClass "midweight" }}
                      cpu_request = "1000m"
                      cpu_limit = "1000m"
                      memory_request = "2Gi"
                      memory_limit = "2Gi"
                      {{- else if eq .parameters.instanceClass "heavyweight" }}
                      cpu_request = "2000m"
                      cpu_limit = "2000m"
                      memory_request = "4Gi"
                      memory_limit = "4Gi"
                      {{- else if eq .parameters.instanceClass "xheavyweight" }}
                      cpu_request = "4000m"
                      cpu_limit = "4000m"
                      memory_request = "8Gi"
                      memory_limit = "8Gi"
                      {{- end }}
                      [runners.kubernetes.node_selector]
                        kubernetes.io/os = "linux"

    # Deployment
    - name: runner-deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners
                annotations:
                  karpenter.sh/do-not-evict: "true"
                  cilium.io/policy-enforced: "true"
                  {{- if eq .parameters.instanceClass "featherweight" }}
                  karpenter.k8s.aws/instance-type: "t3.micro"
                  {{- else if eq .parameters.instanceClass "midweight" }}
                  karpenter.k8s.aws/instance-type: "t3.medium"
                  {{- else if eq .parameters.instanceClass "heavyweight" }}
                  karpenter.k8s.aws/instance-type: "t3.large"
                  {{- else if eq .parameters.instanceClass "xheavyweight" }}
                  karpenter.k8s.aws/instance-type: "t3.xlarge"
                  {{- end }}
              spec:
                replicas: {{ .parameters.replicas }}
                selector:
                  matchLabels:
                    app: gitlab-runner
                template:
                  metadata:
                    labels:
                      app: gitlab-runner
                      runner-class: {{ .parameters.instanceClass }}
                      department: {{ .parameters.department }}
                      runner-env: {{ .parameters.runnerEnvironment }}
                    annotations:
                      karpenter.sh/do-not-evict: "true"
                      cilium.io/policy-enforced: "true"
                      {{- if eq .parameters.instanceClass "featherweight" }}
                      karpenter.k8s.aws/instance-type: "t3.micro"
                      {{- else if eq .parameters.instanceClass "midweight" }}
                      karpenter.k8s.aws/instance-type: "t3.medium"
                      {{- else if eq .parameters.instanceClass "heavyweight" }}
                      karpenter.k8s.aws/instance-type: "t3.large"
                      {{- else if eq .parameters.instanceClass "xheavyweight" }}
                      karpenter.k8s.aws/instance-type: "t3.xlarge"
                      {{- end }}
                  spec:
                    serviceAccountName: gitlab-runner
                    containers:
                      - name: gitlab-runner
                        image: gitlab/gitlab-runner:latest
                        resources:
                          {{- if eq .parameters.instanceClass "featherweight" }}
                          requests:
                            cpu: "500m"
                            memory: "1Gi"
                          limits:
                            cpu: "500m"
                            memory: "1Gi"
                          {{- else if eq .parameters.instanceClass "midweight" }}
                          requests:
                            cpu: "1000m"
                            memory: "2Gi"
                          limits:
                            cpu: "1000m"
                            memory: "2Gi"
                          {{- else if eq .parameters.instanceClass "heavyweight" }}
                          requests:
                            cpu: "2000m"
                            memory: "4Gi"
                          limits:
                            cpu: "2000m"
                            memory: "4Gi"
                          {{- else if eq .parameters.instanceClass "xheavyweight" }}
                          requests:
                            cpu: "4000m"
                            memory: "8Gi"
                          limits:
                            cpu: "4000m"
                            memory: "8Gi"
                          {{- end }}
                        env:
                          - name: RUNNER_TOKEN
                            valueFrom:
                              secretKeyRef:
                                name: gitlab-runner-token
                                key: runner-token
                        volumeMounts:
                          - name: config-volume
                            mountPath: /etc/gitlab-runner
                    volumes:
                      - name: config-volume
                        configMap:
                          name: gitlab-runner-config
                          items:
                            - key: config.toml
                              path: config.toml
