apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xgitlabrunners-xheavyweight.gitlab.organization.io
spec:
  compositeTypeRef:
    apiVersion: gitlab.organization.io/v1alpha1
    kind: XGitLabRunner
  resources:
    # Namespace
    - name: runner-namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: gitlab-runners

    # Service Account
    - name: runner-sa
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners

    # ConfigMap with runner configuration
    - name: runner-config
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: gitlab-runner-config
                namespace: gitlab-runners
              data:
                config.toml: |
                  concurrent = 4
                  check_interval = 30
                  [[runners]]
                    [runners.kubernetes]
                      image = "ubuntu:22.04"
                      privileged = false
                      namespace = "gitlab-runners"
                      poll_timeout = 600
                      cpu_request = "4000m"
                      cpu_limit = "4000m"
                      memory_request = "8Gi"
                      memory_limit = "8Gi"

    # Deployment
    - name: runner-deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gitlab-runner
                namespace: gitlab-runners
                annotations:
                  karpenter.sh/do-not-evict: "true"
                  cilium.io/policy-enforced: "true"
              spec:
                replicas: 0
                selector:
                  matchLabels:
                    app: gitlab-runner
                template:
                  metadata:
                    labels:
                      app: gitlab-runner
                      runner-class: xheavyweight
                      department: devops
                      runner-env: dev
                    annotations:
                      karpenter.sh/do-not-evict: "true"
                      cilium.io/policy-enforced: "true"
                      karpenter.k8s.aws/instance-type: "t3.xlarge"
                  spec:
                    serviceAccountName: gitlab-runner
                    containers:
                      - name: gitlab-runner
                        image: gitlab/gitlab-runner:latest
                        resources:
                          requests:
                            cpu: "4000m"
                            memory: "8Gi"
                          limits:
                            cpu: "4000m"
                            memory: "8Gi"
                        env:
                          - name: RUNNER_TOKEN
                            valueFrom:
                              secretKeyRef:
                                name: gitlab-runner-token
                                key: runner-token
                        volumeMounts:
                          - name: config-volume
                            mountPath: /etc/gitlab-runner
                    volumes:
                      - name: config-volume
                        configMap:
                          name: gitlab-runner-config
                          items:
                            - key: config.toml
                              path: config.toml
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.replicas
          toFieldPath: spec.forProvider.manifest.spec.replicas
